services:
  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./backend:/var/www
      - ./docker/backend/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/backend/certs:/etc/nginx/certs
    depends_on:
      - backend
    networks:
      - public
      - private

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    container_name: vue_app
    # Pour le hot-reloading
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    networks:
      - public

  backend:
    build:
       context: .
       dockerfile: docker/backend/Dockerfile
    container_name: symfony_app
    expose:
      - "9000"
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
      # Exclure le vendor et les fichiers inutiles pour le développement
      - /var/www/vendor
      - /var/www/var
      - /var/www/node_modules
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pidof php-fpm || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - private

  database:
    image: mysql:latest
    container_name: bdd-roomies
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - database_roomies:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u${MYSQL_USER} -p${MYSQL_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - private

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-roomies
    ports:
      - "8080:80"
    env_file:
      - .env
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - private

  mailpit:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
        - private
        
networks:
  private:
    driver: bridge
  public:
    driver: bridge

volumes:
  database_roomies: