services:
  # nginx:
  #   image: nginx:stable-alpine
  #   container_name: nginx_proxy
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  #     - ./nginx/certs:/etc/nginx/certs:ro
  #     - ./:/var/www:ro
  #   depends_on:
  #     - backend
  #   networks:
  #     - public
  #     - private

  # backend:
  #   build:
  #     context: .
  #   container_name: symfony_app
  #   expose:
  #     - "9000"
  #   working_dir: /var/www
  #   volumes:
  #     - .:/var/www:cached
  #     # - ./:/var/www:delegated
  #     # Exclure le vendor et les fichiers inutiles pour le développement => problème je ne peux pas dechiffrer mon token 
  #     # - /var/www/vendor/
  #     - /var/www/var/
  #     - /var/www/node_modules/
  #   depends_on:
  #     database:
  #       condition: service_healthy
  #   restart: unless-stopped
  #   healthcheck:
  #     test: ["CMD-SHELL", "pidof php-fpm || exit 1"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
  #   networks:
  #     - private

  # database:
  #   image: mysql:latest
  #   container_name: bdd-roomies
  #   env_file:
  #     - .env
  #   environment:
  #     MYSQL_DATABASE: ${MYSQL_DATABASE}
  #     MYSQL_USER: ${MYSQL_USER}
  #     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #   volumes:
  #     - database_roomies:/var/lib/mysql
  #   restart: unless-stopped
  #   healthcheck:
  #     test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u${MYSQL_USER} -p${MYSQL_PASSWORD}"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #   networks:
  #     - private

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin:latest
  #   container_name: phpmyadmin-roomies
  #   ports:
  #     - "8080:80"
  #   env_file:
  #     - .env
  #   environment:
  #     PMA_HOST: database
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  #   networks:
  #     - private

  mailpit:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
#     networks:
#         - private
        
# networks:
#   private:
#     driver: bridge
#   public:
#     driver: bridge

# volumes:
#   database_roomies: