lexik_jwt_authentication:
  secret_key: "%env(resolve:JWT_SECRET_KEY)%"
  public_key: "%env(resolve:JWT_PUBLIC_KEY)%"
  pass_phrase: "%env(JWT_PASSPHRASE)%"
  token_ttl: 3600
  token_extractors:
    authorization_header:
      enabled: false
    cookie:
      enabled: true
      name: BEARER # nom du cookie JWT
  set_cookies:
    BEARER:
      lifetime: 3600 # TTL en secondes
      samesite: strict
      path: /
      secure: true
      httpOnly: true
  remove_token_from_body_when_cookies_used: false
