nelmio_cors:
  defaults:
    allow_origin: ["http://localhost:5173"]
    allow_methods: ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]
    allow_headers: ["Content-Type", "Authorization", "X-Silent-Auth"]
    expose_headers: ["Content-Type", "Authorization"]
    max_age: 3600
    allow_credentials: true

  paths:
    "^/":
      allow_origin: ["http://localhost:5173"]
      allow_methods: ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]
      allow_headers: ["Content-Type", "Authorization", "X-Silent-Auth"]
      expose_headers: ["Content-Type", "Authorization"]
      allow_credentials: true
